InformationSystem/Controllers/TAPController.cs
using ICCModule;
using ICCModule.ActionFilters;
using ICCModule.Entity.Tables.Platform;
using ICCModule.EntityService.Service;
using ICCModule.Helper;
using ICCModule.Models.Map.Google;
using ICCModule.Models.Map.TGOS;
using ICCModule.ViewModel;
using InformationSystem.ViewModel.TAP;
using IscomG2C.Utility;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace InformationSystem.Controllers
{
    [LoginCheckFilter]//掛載此Filter，如果沒登入，就導去登入頁
    [InterceptorOfController]//系統操作Log
    public class TAPController : Controller
    {
        //產銷履歷產品-列表
        public ActionResult ProductList(resumeProductQueryModel param)
        {
            Expression<Func<resumeProduct, bool>> filter = null;
            if (!string.IsNullOrEmpty(param.KeyWord)) filter = x => x.VendorName.Contains(param.KeyWord) || x.OrganizationCode.Contains(param.KeyWord);

            var data = Service_resumeProduct.GetList(filter, new resumeProductReq
            {
                TagResult = param.TagResult,
                QuilityResult = param.QuilityResult,
                CheckStartDate = param.CheckStartDate,
                CheckEndDate = param.CheckEndDate,
                CheckData = param.CheckData,
            });
            param.resumeProductModels = data.OrderByDescending(x => x.LastCheckDate).ThenByDescending(x => x.CreatedAt).Skip((param.Pages - 1) * 20).Take(20).ToList();
            param.TotalPage = (int)Math.Ceiling((decimal)data.Count() / 20);

            return View(param);
        }


        //農藥販售業者資料
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ProductList(resumeProductQueryModel param, HttpPostedFileBase importFile, string act = "")
        {
            var errMsg = "";
            #region 匯入
            if (importFile != null && act == "upload")
            {
                var fileName = Path.GetFileName(importFile.FileName);
                var fileType = Path.GetExtension(fileName);

                var dt = new DataTable();
                if (fileType.ToLower() == ".xls") dt = ExcelHelper.RenderDataTableFromExcelXls(importFile.InputStream, 0, 0);
                else if (fileType.ToLower() == ".xlsx") dt = ExcelHelper.RenderDataTableFromExcelXlsx(importFile.InputStream, 0, 0);
                else
                {
                    errMsg = "僅接受副檔名為xls與xlsx之檔案";
                }
                if (string.IsNullOrEmpty(errMsg))
                {
                    #region 驗證欄位
                    var missRow = "";
                    var needRow = new List<string>() { "作物類別", "驗證品項", "農業品經營業者名稱", "農業品經營業者地址", "經營業者代碼", "農民姓名", "地段", "地號", "驗證面積", "驗證機構", "驗證到期日", "公開電話" };
                    foreach (DataColumn dtc in dt.Columns)
                    {
                        if (needRow.Contains(dtc.ColumnName)) needRow.Remove(dtc.ColumnName);
                    }
                    if (needRow.Count > 0) errMsg = $"缺少必要欄位:{string.Join(",", needRow)}";
                    #endregion
                    if (string.IsNullOrEmpty(errMsg) && dt.Rows.Count > 0)
                    {
                        for (int i = 0; i < dt.Rows.Count; i++)
                        {
                            var row = dt.Rows[i];
                            if (string.IsNullOrEmpty(row["地號"].ToString()) || string.IsNullOrEmpty(row["地段"].ToString()))
                            {
                                errMsg = "地段、地號為必填欄位";
                            }
                            var _date = Extention.MinToDateTime(row["驗證到期日"].ToString());
                            if (!_date.HasValue) errMsg = "驗證到期日格式不正確(可能是格式錯誤或有多餘欄位未清除)";
                        }
                        if (string.IsNullOrEmpty(errMsg))
                        {
                            var importData = new List<resumeProduct>();
                            for (int i = 0; i < dt.Rows.Count; i++)
                            {
                                var row = dt.Rows[i];

                                float _area = 0;
                                float? _areas = null;
                                if (float.TryParse(row["驗證面積"].ToString(), out _area)) _areas = _area;
                                var _date = Extention.MinToDateTime(row["驗證到期日"].ToString());
                                importData.Add(new resumeProduct()
                                {
                                    OrganizationCode = row["經營業者代碼"].ToString(),
                                    VendorName = row["農業品經營業者名稱"].ToString(),
                                    ProducerName = row["農民姓名"].ToString(),
                                    Address = row["農業品經營業者地址"].ToString(),
                                    Phone = row["公開電話"].ToString(),
                                    VerificationAgency = row["驗證機構"].ToString(),
                                    VerificationTypes = row["作物類別"].ToString(),
                                    VerificationItems = row["驗證品項"].ToString(),
                                    VerificationArea = _areas,
                                    Lot = row["地段"].ToString(),
                                    LandNum = row["地號"].ToString(),
                                    ExpirationDate = _date,
                                    Principal = "",
                                    ContactPerson = ""
                                });
                            }
                            errMsg = Service_resumeProduct.Import(importData).Msg;
                        }
                    }
                }
            }
            #endregion
            Expression<Func<resumeProduct, bool>> filter = null;
            if (!string.IsNullOrEmpty(param.KeyWord)) filter = x => x.VendorName.Contains(param.KeyWord) || x.OrganizationCode.Contains(param.KeyWord);

            var otherParam = new resumeProductReq
            {
                TagResult = param.TagResult,
                QuilityResult = param.QuilityResult,
                CheckStartDate = param.CheckStartDate,
                CheckEndDate = param.CheckEndDate,
                CheckData = param.CheckData,
            };
            var data = Service_resumeProduct.GetList(filter, otherParam);
            param.resumeProductModels = data.OrderByDescending(x => x.LastCheckDate).ThenByDescending(x => x.CreatedAt).Skip((param.Pages - 1) * 20).Take(20).ToList();
            param.TotalPage = (int)Math.Ceiling((decimal)data.Count() / 20);

            #region 匯出
            if (act == "export")
            {
                var exportData = Service_resumeProduct.GetExportList(filter, otherParam);
                var _export = exportData.Select(x => new
                {
                    組織代碼 = x.OrganizationCode,
                    業者名稱 = x.VendorName,
                    生產者名稱 = x.ProducerName,
                    驗證品項 = x.VerificationItems,
                    驗證面積 = !x.VerificationArea.HasValue ? "" : x.VerificationArea.Value.ToString(),
                    地段 = x.Lot,
                    地號 = x.LandNum,
                    驗證到期日 = !x.ExpirationDate.HasValue ? "" : x.ExpirationDate.Value.ToString("yyyy-MM-dd"),
                    檢查日期 = !x.Date.HasValue ? "" : x.Date.Value.ToString("yyyy-MM-dd"),
                    標示檢查結果 = !x.TagResult.HasValue ? "" : ((x.TagResult ?? true) ? "合格" : "不合格"),
                    品質檢查結果 = !x.QuilityResult.HasValue ? "" : ((x.QuilityResult ?? true) ? "合格" : "不合格"),
                    裁處說明 = x.ArbitrationInstructions
                }).OrderBy(x => x.業者名稱).ThenBy(x => x.檢查日期).ToList();

                return File(ExcelHelper.RenderDataTableToExcel(ExcelHelper.ConvertToDataTable(_export)), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"產銷履歷檢查紀錄_{DateTime.Now.ToString("yyyyMMddHHmmss")}.xlsx");
            }
            #endregion

            if (!string.IsNullOrEmpty(errMsg))
            {
                TempData["TempMsg"] = errMsg;
                TempData["TempResult"] = "error";
            }

            return View(param);
        }

        //產銷履歷產品-內容
        public ActionResult ProductInfo(int id=0)
        {
            var _res = new resumeProductEditModel();
            var _data = Service_resumeProduct.GetDetail(id);
            if (_data != null)
            {
                _res = new resumeProductEditModel
                {
                    ID = _data.ID,
                    OrganizationCode = _data.OrganizationCode,
                    VendorName = _data.VendorName,
                    ProducerName = _data.ProducerName,
                    Principal = _data.Principal,
                    ContactPerson = _data.ContactPerson,
                    Address = _data.Address,
                    Phone = _data.Phone,
                    VerificationAgency = _data.VerificationAgency,
                    VerificationTypes = _data.VerificationTypes,
                    VerificationItems = _data.VerificationItems,
                    VerificationArea = _data.VerificationArea,
                    Lot = _data.Lot,
                    LandNum = _data.LandNum,
                    ExpirationDate = _data.ExpirationDate,
                    ActionName = ""
                };
            }
            return View(_res);
        }
        //產銷履歷產品-內容
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ProductInfo(resumeProductEditModel req)
        {
            var data = new resumeProduct
            {
                ID = req.ID,
                OrganizationCode = req.OrganizationCode,
                VendorName = req.VendorName,
                ProducerName = req.ProducerName,
                Principal = req.Principal,
                ContactPerson = req.ContactPerson,
                Address = req.Address,
                Phone = req.Phone,

InformationSystem/Views/TAP/AuditorInfo.cshtml
@model InformationSystem.ViewModel.TAP.resumeProductCheckEditModel
@{
    ViewBag.Title = "AuditorInfo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Style {
    <style>
        .form-control.error {
            border-color: red;
            border-width: 2px;
            font-size: 1rem;
            width: 100%;
        }

        .form-inline .form-control.error {
            width: auto;
        }

        label.error {
            color: red;
            font-size: 14px;
        }

        .error-border {
            border-color: red;
            border-width: 2px;
        }
    </style>
}

<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-success">產銷履歷產品-@(Model.ID>0?"編輯":"新增")檢查紀錄</h1>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3 bg-white">
                    <form id="form" method="post" enctype="multipart/form-data">
                        @Html.AntiForgeryToken()
                        <div class="card-body">
                            <div class="table-responsive card">
                                <input type="hidden" name="ID" value="@Model.ID" />
                                <input type="hidden" name="ProductID" value="@Model.ProductID" />
                                <table class="table mb-0 no-border">
                                    <tr>
                                        <th style="width:15%">
                                            <span class="important">檢查日期：</span>
                                        </th>
                                        <td style="width:40%">
                                            <input type="date" class="form-control" name="Date" value="@Model.Date.ToString("yyyy-MM-dd")" required title="檢查日期為必填欄位" />
                                        </td>
                                        <th style="width:50%"></th>
                                    </tr>
                                    <tr>
                                        <th>
                                            <span>標示結果：</span>
                                        </th>
                                        <td>
                                            <div class="form-inline">
                                                <label class="mr-2"><input type="radio" class="form-control mr-2" @(Model.TagResult == true ? "checked" : "") name="TagResult" value="true" />合格</label>
                                                <label class="mr-2"><input type="radio" class="form-control mr-2" @(Model.TagResult == true ? "" : "checked") name="TagResult" value="false" />不合格</label>
                                            </div>
                                        </td>
                                        <th></th>
                                    </tr>
                                    <tr>
                                        <th>
                                            <span>品質結果：</span>
                                        </th>
                                        <td>
                                            <div class="form-inline">
                                                <label class="mr-2"><input type="radio" class="form-control mr-2" @(Model.QuilityResult == true ? "checked" : "") name="QuilityResult" value="true" />合格</label>
                                                <label class="mr-2"><input type="radio" class="form-control mr-2" @(Model.QuilityResult == true ? "" : "checked") name="QuilityResult" value="false" />不合格</label>
                                            </div>
                                        </td>
                                        <th></th>
                                    </tr>
                                    <tr>
                                        <th>
                                            <span>裁處情形(說明)：</span>
                                        </th>
                                        <td>
                                            <textarea class="form-control" rows="6" name="ArbitrationInstructions">@Model.ArbitrationInstructions</textarea>
                                        </td>
                                        <th></th>
                                    </tr>
                                    <tr>
                                        <th>
                                            <span>檢查文件檔案上傳：</span>
                                        </th>
                                        <td>
                                            <div class="form-inline">
                                                @foreach (var item in Model.OldFiles)
                                                {
                                                    <div id="of_@item.ID">
                                                        @Html.Hidden("EditOldFiles[]", item.ID, new { @id = "of_" + item.ID })
                                                        <a href="@item.FilePath" target="_blank">@item.FileName</a><a class="btn" onclick="DelFile('of_@item.ID')">x</a>
                                                    </div>
                                                }
                                                <input type="file" multiple name="NewFiles" accept=".doc, .docx, .odt, .ods, .ppt, .pdf, .xls, .xlsx, .jpg, .png, .jpeg, .csv, .gif, .txt" />
                                                @*<input type="file" class="form-control" />
                                                    <button type="button" class="btn btn-primary ml-2">更多檔案</button>*@
                                            </div>
                                        </td>
                                        <th></th>
                                    </tr>
                                </table>
                            </div>
                            <div style="display:flex;justify-content:center">
                                <button type="button" class="btn btn-primary m-2" onclick="handleSubmit(event)">儲存</button>
                                <button type="button" class="btn btn-primary m-2" onclick="window.history.back()">回上一頁</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@section Script{
    <script>
        function handleSubmit(e) {
            e.preventDefault();
            var validate = $("form").valid();
            if (validate) {
                console.log($('form').serializeArray())
                document.getElementById('form').submit();
            }
        }
        function DelFile(id) {
            $('#' + id).html('');
        }
    </script>
}
<!-- 功能執行警示結果 -->
@{
    string strTempMsg = (TempData["TempMsg"] == null) ? "" : TempData["TempMsg"].ToString();
    TempData["TempMsg"] = null;
    //取代換行
    strTempMsg = strTempMsg.Replace("\r\n", " ");
    strTempMsg = strTempMsg.Replace("\n", " ");
}
<script type="text/javascript">
        var sMessage = "@strTempMsg";
        if (sMessage.length > 0) {
            setTimeout("alert(sMessage)", 500);
        }
</script>

InformationSystem/Views/TAP/AuditorList.cshtml
@model InformationSystem.ViewModel.TAP.resumeProductCheckListModel
@{
    ViewBag.Title = "AuditorList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-success">產銷履歷產品-檢查紀錄列表</h1>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3 bg-white">
                    <div class="card-body">
                        <div class="table-responsive card">
                            <table class="table mb-0 no-border">
                                <tr>
                                    <th>
                                        <span>組織代碼</span>
                                    </th>
                                    <td>
                                        <span>@Model.OrganizationCode</span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        <span>經營業者名稱</span>
                                    </th>
                                    <td>@Model.VendorName</td>
                                </tr>
                            </table>
                        </div>
                        <div style="display:flex">
                            <div style="margin-left:auto">
                                <button type="button" class="btn btn-primary m-2" onclick="location.href='/TAP/AuditorInfo?pid=@Model.ProductId'"><i class="fas fa-plus-circle mr-2"></i>新增</button>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table mb-0 table-striped" style="min-width:700px;">
                                <thead class="thead-light">
                                    <tr>
                                        <th scope="col">項次</th>
                                        <th scope="col">檢查日期</th>
                                        <th scope="col">標示結果</th>
                                        <th scope="col">品質結果</th>
                                        <th scope="col">裁處情形(說明)</th>
                                        <th scope="col">功能</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.resumeProductChecks)
                                    {
                                        int i = 0;
                                        <tr>
                                            <td>i</td>
                                            <td>@item.Date.ToString("yyyy-MM-dd")</td>
                                            <td>@(!item.TagResult.HasValue ? "": (item.TagResult == true ?"合格":"不合格"))</td>
                                            <td>@(!item.QuilityResult.HasValue ? "" : (item.QuilityResult == true ? "合格" : "不合格"))</td>
                                            <td>@item.ArbitrationInstructions</td>
                                            <td>
                                                <div class="form-inline">
                                                    <button type="button" class="btn btn-danger m-2" onclick="location.href='/TAP/AuditorInfo?Id=@item.ID&pid=@item.ProductID'">編輯</button>
                                                    @using (Html.BeginForm("AuditorDelete", "TAP", FormMethod.Post, new { onclick = "return confirm('確定刪除?');" }))
                                                    {
                                                        @Html.Hidden("Id", item.ID)
                                                        @Html.Hidden("pid", item.ProductID)
                                                        <button type="submit" class="btn btn-secondary m-2">刪除</button>
                                                    }
                                                </div>
                                            </td>
                                        </tr>
                                        i++;
                                    }

                                </tbody>
                            </table>
                        </div>
                        <div class="form-inline" style="justify-content:center">
                            <button type="button" class="btn btn-primary m-2" onclick="location.href='/TAP/ProductList'">回上一頁</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>