InformationSystem/Controllers/PlantManagerController.cs
using ICCModule.ActionFilters;
using ICCModule.Entity.Tables.Platform;
using ICCModule.EntityService.Service;
using ICCModule.Helper;
using InformationSystem.ViewModel.Management;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security.AntiXss;

namespace InformationSystem.Controllers
{
    [LoginCheckFilter]//掛載此Filter，如果沒登入，就導去登入頁
    [InterceptorOfController]//系統操作Log
    public class PlantManagerController : Controller
    {
        //作物類別資料
        public ActionResult Category()
        {
            var _res = Service_cropType.GetList(null).OrderBy(x => x.Sort).ToList();
            return View(_res);
        }
        //作物類別編輯
        public ActionResult CategoryEdit(int id = 0)
        {
            var _res = Service_cropType.GetDetail(id) ?? new cropType();
            return View(_res);
        }
        //作物類別編輯-儲存
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CategoryEdit(cropType cropTypeModel)
        {
            if (cropTypeModel.ID > 0 && Service_cropType.GetDetail((int)cropTypeModel.ID) != null)
            {
                Service_cropType.Update(cropTypeModel);
            }
            else
            {
                Service_cropType.Insert(cropTypeModel);
            }

            return RedirectToAction(nameof(Category));
        }

        //作物內容
        public ActionResult PlantData(int tid)
        {
            if (Service_cropType.GetDetail(tid) == null) return RedirectToAction(nameof(Category));

            var _res = new PlantListViewModel()
            {
                crops = Service_crops.GetList(x => x.TypeID == tid).OrderBy(x => x.Sort).ToList(),
                TypeId = tid
            };
            return View(_res);
        }
        //作物內容編輯
        public ActionResult PlantEdit(int id = 0, int tid = 0)
        {
            var cTypes = Service_cropType.GetDetail(tid);
            if (cTypes == null) return RedirectToAction(nameof(Category));

            var _res = Service_crops.GetDetail(id) ?? new crops();
            _res.TypeID = cTypes.ID;
            return View(_res);
        }
        //作物內容編輯-儲存
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PlantEdit(crops cropsModel)
        {
            if (cropsModel.ID > 0 && Service_crops.GetDetail((int)cropsModel.ID) != null)
            {
                Service_crops.Update(cropsModel);
            }
            else
            {
                Service_crops.Insert(cropsModel);
            }

            return RedirectToAction(nameof(PlantData), new { tid = cropsModel.TypeID });
        }

        //防治曆-List
        public ActionResult CalendarList()
        {
            var _res = Service_controlHistory.GetList(null);
            return View(_res);
        }
        [HttpPost] //刪除方法為POST
        public ActionResult CalendarDelete(int Id)
        {
            if (Service_controlHistory.GetDetail(Id) != null)
            {
                var chc = Service_controlHistoryCrop.GetList(x => x.ControlID == Id);
                if (chc.Any())
                {
                    var chcc = Service_controlHistoryCropsContents.GetList(x => chc.Select(o => o.ID).Contains(x.ControlHistoryCropId));
                    if (chcc.Any())
                    {
                        var _rt1 = Service_controlHistoryCropsContents.DeleteMany(x => chc.Select(o => o.ID).Contains(x.ControlHistoryCropId));
                    }
                    var _rt2 = Service_controlHistoryCrop.DeleteMany(x => x.ControlID == Id);
                }
                Service_controlHistory.Delete(Id);
            }
            return RedirectToAction(nameof(CalendarList));
        }
        //防治曆-內頁
        public ActionResult CalendarInfo(int Id = 0)
        {
            var _response = new CalendarEditModel();
            var cHistory = Service_controlHistory.GetDetail(Id);
            if (cHistory != null)
            {
                _response = new CalendarEditModel
                {
                    ID = cHistory.ID,
                    Name = cHistory.Name,
                    Type = cHistory.Type,
                    Enable = cHistory.Enable,
                    Information = cHistory.Information,
                    Explanation = cHistory.Explanation,
                    ControlHistoryCrops = Service_controlHistoryCrop.GetList(x => x.ControlID == cHistory.ID)
                };
            }
            return View(_response);
        }
        //作物內容編輯-儲存
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult CalendarInfo(CalendarEditModel calendarModel)
        {
            var oldData = Service_controlHistory.GetDetail((int)calendarModel.ID);
            if (calendarModel.ID > 0 && oldData != null)
            {
                oldData.Name = calendarModel.Name;
                oldData.Type = calendarModel.Type;
                oldData.Enable = calendarModel.Enable;
                oldData.Information = calendarModel.Information;
                oldData.Explanation = calendarModel.Explanation;
                Service_controlHistory.Update(oldData);
            }
            else
            {
                var newData = new controlHistory();
                newData.Name = calendarModel.Name;
                newData.Type = calendarModel.Type;
                newData.Enable = calendarModel.Enable;
                newData.ClickCount = 0;
                newData.Information = calendarModel.Information;
                newData.Explanation = calendarModel.Explanation;
                Service_controlHistory.Insert(newData);
                calendarModel.ID = Service_controlHistory.GetList(null).OrderByDescending(x => x.CreatedAt).FirstOrDefault().ID;
            }
            if (calendarModel.ActionName == "Add")
                return RedirectToAction(nameof(CalendarAdd), new { cid = calendarModel.ID });
            else if (calendarModel.ActionName == "Update")
                return RedirectToAction(nameof(CalendarAdd), new { cid = calendarModel.ID, id = calendarModel.ControlHistoryCropId });

            return RedirectToAction(nameof(CalendarList));
        }
        //防治曆-新增
        public ActionResult CalendarAdd(int cid = 0, int id = 0)
        {
            var getControlHistory = Service_controlHistory.GetDetail((int)cid);
            if (getControlHistory == null) return RedirectToAction(nameof(CalendarList));

            var data = Service_controlHistoryCrop.GetDetail(id);
            var _res = new ControlHistoryCropEditModel();
            _res.ControlID = cid;

            if (data != null)
            {
                _res = new ControlHistoryCropEditModel()
                {
                    ID = data.ID,
                    ControlID = data.ControlID,
                    Name = data.Name,
                    Sort = data.Sort,
                    Show = data.Show,
                    Type = data.Type,
                    Comment = data.Comment,
                    Context = data.Context,
                    DayCount = data.DayCount,
                };

                var contentsData = Service_controlHistoryCropsContents.GetList(x => x.ControlHistoryCropId == _res.ID);
                var cHeader = new List<CollumHead>();
                var cGroup = new List<ContentGroup>();
                if (contentsData.Any())
                    if (_res.Type)
                    {
                        for (var i = 0; i <= 12; i++)
                        {
                            if (i == 0) cHeader.Add(new CollumHead { CollumName = "防治曆", Sort = i });
                            else cHeader.Add(new CollumHead { CollumName = $"{i}月", Sort = i });
                        }
                        _res.CollumHeads = cHeader;
                        _res.ContentGroups = contentsData.GroupBy(x => x.ControlStage).Select(item => new ContentGroup()
                        {
                            ContentName = item.Key,
                            Sort = item.Key == "生長期" ? 1 : (item.Key == "生活史" ? 2 : (item.Key == "慣行栽植" ? 3 : 4)),
                            ContentDatas = item.Select(x => new ContentData
                            {
                                Id = x.Id,
                                Name = x.Name,
                                Width = (x.EndBlock.DateToDecimal() - x.StartBlock.DateToDecimal()) * 100,
                                Margin = (x.StartBlock.DateToDecimal() - x.StartBlock.ToDateTime()?.Month ?? 0) * 100,
                                Sort = x.StartBlock.ToDateTime()?.Month ?? 0,
                                ShowType = x.ShowType,
                                StartDate = x.StartBlock.ToDateTime().Value,
                                EndDate = x.EndBlock.ToDateTime().Value,
                            }).OrderBy(x => x.Sort).ToList()
                        }).ToList();

                        int s = 1;
                        var newContentGroup = new List<ContentGroup>();
                        foreach (var item in _res.ContentGroups)
                        {
                            var j = 0;
                            var exceptId = new List<int>();
                            var oldContentData = new List<ContentData>();
                            foreach (var itemData in item.ContentDatas)
                            {
                                if (s != itemData.Sort) j = 0;
                                s = itemData.Sort;
                                var newData = new List<ContentData>();
                                if (oldContentData.Where(x => !exceptId.Contains(x.Id)).Any(x => x.Sort < s && (Math.Max(x.StartDate.Ticks, itemData.StartDate.Ticks) < Math.Min(x.EndDate.Ticks, itemData.EndDate.Ticks))))
                                {

InformationSystem/Views/PlantManager/CalendarAdd.cshtml
@model InformationSystem.ViewModel.Management.ControlHistoryCropEditModel
@{
    ViewBag.Title = "CalendarAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section HeadScript {
    <script src="~/js/html2canvas.js"></script>
}
@section Style {
    <style>
        .form-control.error {
            border-color: red;
            border-width: 2px;
            font-size: 1rem;
            width: 100%;
        }

        .form-inline .form-control.error {
            width: auto;
        }

        label.error {
            color: red;
            font-size: 14px;
        }

        .error-border {
            border-color: red;
            border-width: 2px;
        }
    </style>
}

<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-success">新增防治曆</h1>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <form id="form" method="post" enctype="multipart/form-data">
                    @Html.AntiForgeryToken()
                    <div class="card-header py-3 bg-white">
                        <div class="card-body">
                            <input type="hidden" name="ID" value="@Model.ID" />
                            <input type="hidden" name="ControlID" value="@Model.ControlID" />
                            <div class="table-responsive card">
                                <table class="table mb-0 no-border">
                                    <tr>
                                        <td colspan="4" style="text-align:right">
                                            <a class="btn btn-primary m-2" href="/PlantManager/CalendarInfo?Id=@Model.ControlID">回上一頁</a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th style="width:10%">
                                            <label class="important">防治曆名稱</label>
                                        </th>
                                        <td style="width:40%">
                                            <input type="text" id="calname" class="form-control" value="@Model.Name" name="Name" required title="名稱為必填欄位" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <th style="width:10%">
                                            <label class="important">排序值</label>
                                        </th>
                                        <td style="width:40%">
                                            <input type="number" class="form-control" value="@Model.Sort" name="Sort" required title="排序為必填欄位" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <th style="width:10%">
                                            <label class="important">前台顯示</label>
                                        </th>
                                        <td style="width:40%">
                                            <div class="form-inline">
                                                <label class="mr-2"><input type="radio" class="mr-2" name="Show" @(Model.Show ? "checked" : "") value="true" />是</label>
                                                <label class="mr-2"><input type="radio" class="mr-2" name="Show" @(!Model.Show ? "checked" : "") value="false" />否</label>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th style="width:10%">
                                            <label class="important">防治類型</label>
                                        </th>
                                        <td style="width:40%">
                                            <div class="form-inline">
                                                <label class="mr-2"><input type="radio" class="mr-2" name="Type" @(Model.Type ? "checked" : "") value="true" onclick="$('#day_count').hide();" />月曆</label>
                                                <label class="mr-2"><input type="radio" class="mr-2" name="Type" @(!Model.Type ? "checked" : "") value="false" onclick="$('#day_count').show();" />日曆</label>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr id="day_count" style="@(Model.Type ? "display:none;" : "")">
                                        <th style="width:10%">
                                            <label class="important">生育日數</label>
                                        </th>
                                        <td style="width:40%">
                                            <input type="number" class="form-control" value="@Model.DayCount" name="DayCount" min="10" required />
                                        </td>
                                    </tr>
                                    <tr>
                                        <th style="width:10%">
                                            <label>備註：</label>
                                        </th>
                                        <td style="width:40%">
                                            <textarea class="form-control" rows="3" name="Comment">@Model.Comment</textarea>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="4" style="text-align:right">
                                            <button type="submit" class="btn btn-primary m-2" onclick="handleSubmit(event,'','')"><i class="fas fa-search mr-2"></i>儲存</button>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <input id="hidActionName" type="hidden" name="ActionName" value="@Model.ActionName" />
                            <input id="hidContentId" type="hidden" name="ContentId" value="@Model.ContentId" />
                            <div style="display:flex">
                                <button type="button" class="btn btn-primary m-2" onclick="handleSubmit(event,'Add','')"><i class="fas fa-download mr-2"></i>新增防治內容</button>
                                @if (Model.CollumHeads.Any())
                                {
                                    <div style="margin-left:auto">
                                        <a class="btn btn-primary m-2" onclick="htmlToJpg()">下載防治曆</a>
                                    </div>
                                }
                            </div>
                            <div class="table-responsive" id="html-content-holder">
                                <table class="table table-bordered grow">
                                    <thead class="thead-dark">
                                        <tr>
                                            @foreach (var item in Model.CollumHeads.OrderBy(x => x.Sort).ToList())
                                            {
                                                <th>@item.CollumName</th>
                                            }
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.ContentGroups.OrderBy(x => x.Sort).ToList())
                                        {
                                            <tr class="bg-light">
                                                <th scope="row">@item.ContentName</th>
                                                @for (int i = 1; i <= (Model.CollumHeads.Count > 12 ? 12 : 10); i++)
                                                {
                                                    <td>
                                                        @{
                                                            foreach (var data in item.ContentDatas.Where(x => x.Sort == i))
                                                            {
                                                                if (data.ShowType)
                                                                {
                                                                    <div onclick="handleSubmit(event, 'Update', '@data.Id')" class="progress-box grow" style="@($"width:{data.Width}%;left:{data.Margin}%;")">@data.Name</div>
                                                                }
                                                                else
                                                                {
                                                                    <div onclick="handleSubmit(event, 'Update', '@data.Id')" class="progress-box life01" data-toggle="tooltip" data-placement="top" title="@data.Name" style="@($"width:{data.Width}%;left:{data.Margin}%;")">@data.Name</div>
                                                                }
                                                            }
                                                        }
                                                    </td>
                                                }
                                            </tr>
                                        }
                                        @*<td>
                                                <div class="progress-box grow" style="width:150%;">花芽生理分化期</div>
                                            </td>*@
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Script {
    <script>
        function handleSubmit(e, action, id) {
            e.preventDefault();
            var validate = $("form").valid();
            if (validate) {
                if (action) $('#hidActionName').val(action);
                if (id) $('#hidContentId').val(id);

                console.log($('form').serializeArray())
                document.getElementById('form').submit();
            }
        }

        function htmlToJpg() {
            html2canvas(document.getElementById("html-content-holder")).then(function (canvas) {
                var anchorTag = document.createElement("a");
                document.body.appendChild(anchorTag);
                //document.getElementById("previewImg").appendChild(canvas);
                anchorTag.download = $('#calname').val() + ".jpg";
                anchorTag.href = canvas.toDataURL();
                anchorTag.target = '_blank';
                anchorTag.click();
            });
        }
    </script>
}
<!-- 功能執行警示結果 -->
@{
    string strTempMsg = (TempData["TempMsg"] == null) ? "" : TempData["TempMsg"].ToString();
    TempData["TempMsg"] = null;
    //取代換行
    strTempMsg = strTempMsg.Replace("\r\n", " ");
    strTempMsg = strTempMsg.Replace("\n", " ");
}
<script type="text/javascript">
        var sMessage = "@strTempMsg";
        if (sMessage.length > 0) {
            setTimeout("alert(sMessage)", 500);
        }
</script>

InformationSystem/Views/PlantManager/CalendarList.cshtml
@model List<ICCModule.Entity.Tables.Platform.controlHistory>
@{
    ViewBag.Title = "CalendarList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-success">防治曆</h1>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3 bg-white">
                    <div class="card-body">
                        <div style="display:flex">
                            <div style="margin-left:auto">
                                <button type="button" class="btn btn-primary m-2" onclick="location.href='/PlantManager/CalendarInfo'"><i class="fas fa-plus-circle mr-2"></i>新增防治對象</button>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table mb-0 table-striped" style="min-width:700px;">
                                <thead class="thead-light">
                                    <tr>
                                        <th scope="col">防治對象</th>
                                        <th scope="col">類型</th>
                                        <th scope="col">狀態</th>
                                        <th scope="col">動作</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Name</td>
                                            <td>@item.Type</td>
                                            <td>@(item.Enable?"啟用":"停用")</td>
                                            <td>
                                                <div class="form-inline">
                                                    <button type="button" class="btn btn-danger m-2" onclick="location.href='/PlantManager/CalendarInfo?id=' + @item.ID">編輯</button>
                                                    @using (Html.BeginForm("CalendarDelete", "PlantManager", FormMethod.Post, new { onclick = "return confirm('確定刪除?');" }))
                                                    {
                                                        @Html.Hidden("Id", item.ID)
                                                        <input type="submit" class="btn btn-secondary m-2" value="刪除" />
                                                        @*<button type="button" class="btn btn-secondary m-2">刪除</button>*@
                                                    }
                                                </div>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

InformationSystem/Views/PlantManager/Category.cshtml
@model IEnumerable<ICCModule.Entity.Tables.Platform.cropType>
@{
    ViewBag.Title = "Category";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-success">作物類別資料</h1>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3 bg-white">
                    <div class="card-body">
                        <div style="display:flex">
                            <div style="margin-left:auto">
                                <button type="button" class="btn btn-primary m-2" onclick="location.href='/PlantManager/CategoryEdit'"><i class="fas fa-plus-circle mr-2"></i>新增作物類別</button>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table mb-0 table-striped" style="min-width:700px;">
                                <thead class="thead-light">
                                    <tr>
                                        <th scope="col">作物類別</th>
                                        <th scope="col">類別排序</th>
                                        <th scope="col">狀態</th>
                                        <th scope="col">動作</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Name</td>
                                            <td>@item.Sort</td>
                                            <td>@(item.Enable?"啟用":"停用")</td>
                                            <td>
                                                <div class="form-inline">
                                                    <button type="button" class="btn btn-danger m-2" onclick="location.href='/PlantManager/CategoryEdit?id='+@item.ID">編輯類別</button>
                                                    <button type="button" class="btn btn-primary m-2" onclick="location.href='/PlantManager/PlantData?tid='+@item.ID">作物設定</button>
                                                </div>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

InformationSystem/Views/PlantManager/PlantData.cshtml
@model InformationSystem.ViewModel.Management.PlantListViewModel
@{
    ViewBag.Title = "PlantData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-success">作物類別資料-作物設定</h1>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3 bg-white">
                    <div class="card-body">
                        <div style="display:flex">
                            <div style="margin-left:auto">
                                <button type="button" class="btn btn-primary m-2" onclick="location.href='/PlantManager/PlantEdit?tid=' + @Model.TypeId"><i class="fas fa-plus-circle mr-2"></i>新增作物</button>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table mb-0 table-striped" style="min-width:700px;">
                                <thead class="thead-light">
                                    <tr>
                                        <th scope="col">作物名稱</th>
                                        <th scope="col">類別排序</th>
                                        <th scope="col">狀態</th>
                                        <th scope="col">動作</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.crops)
                                    {
                                        <tr>
                                            <td>@item.Name</td>
                                            <td>@item.Sort</td>
                                            <td>@(item.Enable?"啟用":"停用")</td>
                                            <td>
                                                <div class="form-inline">
                                                    <button type="button" class="btn btn-danger m-2" onclick="location.href='/PlantManager/PlantEdit?id=' + @item.ID + '&tid=' + @Model.TypeId">編輯</button>
                                                </div>
                                            </td>
                                        </tr>
                                    }
                                    <tr>
                                        <td colspan="4">
                                            <div style="display:flex;justify-content:center">
                                                <a class="btn btn-primary m-2" href="/PlantManager/Category">回上一頁</a>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>